dotenv: .env

project_structure:
    build: src/artifacts

# networks:
#     default: development
#     development:
#         cmd_settings:
#             port: 7545
#             network_id: 5777
#             host: 127.0.0.1
